### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by alexyslozada** [gophercises/pdf#1]
https://github.com/gophercises/pdf/blob/93d00b1bf0fc83cc7dd956da162edfe1e6f90519/main.go#L135

This line can be changed to:
df := time.Now().Format("02/01/2006")

**Comment by joncalhoun** [comment]
Thanks! At the time I was recording I blanked. I don't know why, but when recording it is easy to forget silly things like simple algebra or dates. The worst part is I think I have a date plugin installed in vscode for Go to simplify this all!

Anyway, while I do appreciate the code suggestion, I'm not going to update the actual code because I want it to match the code used in the video. At some point I should do a "refactor & review" of all the code from these exercises though, and it would fit in well there 😄

**Comment by alexyslozada** [comment]
Of course I understand it. It also happens to me when I make the videos for my channel. If I do the video live, I do not change anything, but if I record it I edit the pieces in which I do not do things well, however I like your style a lot since there is no editing and those moments of doubt are also valid. Thank you very much for the content created. PS: I'm using google translate to comment, I hope there are not many translation errors

**Comment by joncalhoun** [comment]
Thank you for the kind words and the translations are great :)
